artifacts:
  ARTIFACTS_DIR: artifacts
  RAW_DATA_DIR: data
  RAW_DATA: archive.zip
  EXTRACTED_DATA_DIR: extracted_data_dir
  PROCESSED_DATA_DIR: processed_data_dir
  INPUT_FEATURE: processed_X.csv
  OUTPUT_FEATURE: processed_Y.csv
  TRAINING_DATA: aps_failure_training_set.csv
  CLEANED_CSV_FILE: cleaned.csv
  PREPARED_DATA_DIR:  prepared
  TRAINING_DATA_DIR:  training_data
  LABEL_TRAINING_DATA:  y_data.npy
  IMG_TRAINING_DATA:  x_data.npy
  TRAINED_MODEL_DIR: model
  BASE_MODEL_NAME: resnet_50.h5
  CHECKPOINT_DIR: checkpoints
  BASE_LOG_DIR: base_model_dir
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks

metrics:
  SCORES: scores.json

plots:
  PRC: prc.json
  ROC: roc.json

